### ISSUE TITLE
CommunityVisibilityState maps to non-official values

### ISSUE THREAD

**Issue by MushOP** [Levitas/PortableSteam#1]
The enum CommunityVisibilityState does not represent the values that the official Steam API use as described here: https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

"This represents whether the profile is visible or not, and if it is visible, why you are allowed to see it. Note that because this WebAPI does not use authentication, there are only two possible values returned: 1 - the profile is not visible to you (Private, Friends Only, etc), 3 - the profile is "Public", and the data is visible. Mike Blaszczak's post on Steam forums says, "The community visibility state this API returns is different than the privacy state. It's the effective visibility state from the account making the request to the account being viewed given the requesting account's relationship to the viewed account."

That is
1: Private
3: Public

But the enum CommunityVisibilityState has the following:
1: Private
2: Friends only
3: Friends of friends
4: Users only
5: Public

So when calling GetPlayerSummaries, the value returned in the CommunityVisibilityState, for instance 3 when profile is public, does not represent the correct enum value.

**Comment by VitoHusky** [comment]
hi,

thanks for your report, i will update this issue in a few minutes :)
