### ISSUE TITLE
GetPlayerSummaries return invalid response

### ISSUE THREAD

**Issue by MushOP** [Levitas/PortableSteam#2]
I made an issue yesterday #1  , where i found out that the enum for the communityvisibilitystate was wrong, it was fixed and that was perfect, but now i have a new issue. I am getting no response from my GetPlayerSummaries, i tried converting back to my previous version (1.0.14.591 --> 1.0.13) and i then get a response back from GetPlayerSummaries.

This is the result from version 1.0.14.591:
```
{
        "response": {
                "players": [

                ]

        }
}
```

This is the result from version 1.0.13:
```
{
        "response": {
                "players": [
                        {
                                "steamid": "76561197989112995",
                                "communityvisibilitystate": 3,
                                "profilestate": 1,
                                "personaname": "Mushzeroa",
                                "lastlogoff": 1494917497,
                                "commentpermission": 1,
                                "profileurl": "http://steamcommunity.com/id/MVPBeep/",
                                "avatar": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/01/0189541ba1a2b7a711f5c1df3f9e78656455e6fd.jpg",
                                "avatarmedium": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/01/0189541ba1a2b7a711f5c1df3f9e78656455e6fd_medium.jpg",
                                "avatarfull": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/01/0189541ba1a2b7a711f5c1df3f9e78656455e6fd_full.jpg",
                                "personastate": 1,
                                "primaryclanid": "103582791454869326",
                                "timecreated": 1175620842,
                                "personastateflags": 0
                        }
                ]

        }
}
```

**Comment by VitoHusky** [comment]
Hey, 

Than my test have failed to, that's bad. 
I will take a look at it, thanks for issue

**Comment by VitoHusky** [comment]
At this point the documentation seems to be unclear.
On the the Steam site it says "only private or public" on this site it says 5 different states: https://wiki.teamfortress.com/wiki/WebAPI/GetPlayerSummaries

I set it to 3 different states that i got on my testing (1 = private, 2: FriendsOnly, 3: Public / Visible)

Please try to update. If this issue persists, feel free to reopen the issue.
The new Tests project has the test method for "GetPlayerSummaries()" you can see my issued code there.

**Comment by MushOP** [comment]
I just updated to the latest version and i still seem to get no response.

**Comment by VitoHusky** [comment]
I´m very sorry, but i cannot reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/6342317/26156299/23084db6-3b16-11e7-837c-aa9ba2b0e69d.png)

I tried this code and got a response.

Which version of Visual studio are you running? Im using VS2017 with MSBuild 15 (the package was build with msbuild 14.

**Comment by MushOP** [comment]
Hello
I verified that your code works, and that i get a player result out of it. But using the following code i get no players and the exception gets thrown.

![error](https://cloud.githubusercontent.com/assets/18169683/26164245/60e380e0-3b2c-11e7-8aec-f2709182bd50.png)


```
                    var steamIdentity2 = SteamWebAPI.General().ISteamUser().ResolveVanityURL("gabelogannewell").GetResponse().Data.Identity;
                    var summaries2 = SteamWebAPI.General().ISteamUser().GetPlayerSummaries(steamIdentity2).GetResponse();

                    if (summaries2.Data.Players.Count < 1 || summaries2.Data.Players[0].Identity.SteamID != steamIdentity2.AccountID)
                    {
                        throw new Exception("GetPlayerSummaries2 failed.");
                    }
                    Console.WriteLine($"Player found: {summaries2.Data.Players.Count}");
```
